service: sst-analytics

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1
  environment:
    NODE_ENV: ${env:NODE_ENV}

package:
  exclude:
    - .git/**

functions:
  run:
    handler: handler.run
    description: AWS Lambda function retrieving analytics from Mailchimp and Google Analytics and sent to employees
    events:
      - schedule: cron(0 7 ? * MON *)
