service: sst-analytics

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1

custom:
  schedule:


package:
  exclude:
    - .git/**

functions:
  send:
    handler: handler.send
    description: AWS Lambda function retrieving analytics from Mailchimp and Google Analytics and sent to employees
    events:
      - schedule: ${file(./serverless-schedule.js):${opt:stage}}
    environment:
      NODE_ENV: ${env:NODE_ENV}
