service: sst-analytics

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1
  environment:
    NODE_ENV: ${env:NODE_ENV}

custom:
  schedules:
    production:
      name: mondays-07
      description: 'Triggered every monday at 07:00'
      rate: cron(0 7 ? * MON *)
    dev:
      name: hourly
      description: 'Triggered every hour'
      rate: rate(60 minutes)

package:
  exclude:
    - .git/**

functions:
  send:
    handler: handler.send
    description: AWS Lambda function retrieving analytics from Mailchimp and Google Analytics and sent to employees
    events:
      - schedule: ${self:custom.schedules.${opt:stage}, ${self:custom.schedules.dev}}
