service: sst-analytics

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1

package:
  exclude:
    - .git/**

functions:
  send:
    handler: handler.send
    description: AWS Lambda function retrieving analytics from Mailchimp and Google Analytics and sent to employees
    events:
      - schedule:
        name: mondays-07
        description: 'Triggered every monday at 07:00'
        rate: cron(0 7 ? * MON *)
    environment:
      NODE_ENV: ${env:NODE_ENV}
